# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM continuumio/miniconda3

# Set working directory
WORKDIR /app

# Install RDKit via conda
RUN conda install -y -c conda-forge rdkit=2025.3.5 && \
    conda clean -afy

# Install FastMCP via pip
RUN pip install --no-cache-dir fastmcp

# Copy source code
COPY . /app

# Default command to start the MCP server
CMD ["python", "server.py"]
